//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Haber.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Haberlerim
    {
        public string Hbrid { get; set; }
        public string Haberbaslik { get; set; }
        public string haberadi { get; set; }
        public string Haberkategori { get; set; }
        public string habericeriği { get; set; }
        public string haberyazari { get; set; }
        public System.DateTime habertarihi { get; set; }
    
        public virtual Kategori Kategori { get; set; }
        public virtual Yazar Yazar { get; set; }
    }
}
