//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Haber.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yazar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Yazar()
        {
            this.Haberlerim = new HashSet<Haberlerim>();
        }
    
        public string Yazarid { get; set; }
        public string adsoyad { get; set; }
        public string kayittarih { get; set; }
        public int yas { get; set; }
        public string yazarbrans { get; set; }
        public string sifre { get; set; }
        public string eposta { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Haberlerim> Haberlerim { get; set; }
        public virtual Kategori Kategori { get; set; }
    }
}
